### ISSUE TITLE
List is full of bloatware

### ISSUE THREAD

**Issue by moldux-dartus** [postapczuk/Light-ePaper-Launcher#1]
Could you add a way to exclude some packages from populating in the list? There are a bunch of apps I never use but can't disable because my phone will crash, but I don't want them to appear in the list.

**Comment by postapczuk** [comment]
This is repo is for epaper version designed for ebook readers.

Light Android Launcher is what you need : https://github.com/light-launcher/Light-Android-Launcher

**Comment by moldux-dartus** [comment]
I'm using a hisense a5 pro, the phone has an eink display

**Comment by postapczuk** [comment]
just try the one I've provides you. might fulfill your requirements.
